name: Deploy to Server

on:
  push:
    branches:
      - main
      # - dev
      # - staging

jobs:
  deploy:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # MAIN branch â†’ 2 servers
      - name: Deploy main -> Server A
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@v0.1.4
        with:
          host: "109.123.232.6"
          username: "root"
          key: ${{ secrets.ITT_GIT_SSH_PRIVATE_KEY }}
          source: "."  # optionally limit to src folders
          target: "/var/www/html/cicd-test"
